### ISSUE TITLE
Make a game we can play on the HERA display

### ISSUE THREAD

**Issue by adampbeardsley** [loco-lab/HackProjects#9]

**Comment by adampbeardsley** [comment]
HERA pong

**Comment by mickeyhorn** [comment]
Multiplayer snake! Scribbl.io if you’re confused

**Comment by mickeyhorn** [comment]
One of my friends suggested Duck Hunt, we'd have to build our own light gun though (so probably a longer term project than is suitable for hackday).
https://youtu.be/Nu-Hoj4EIjU?t=550

**Comment by adampbeardsley** [comment]
Ok, we've managed to make a crude duck hunt, and a pretty good snake. The more important thing is that we have a decent game engine to spin up more games fairly easily.
I'm just going to link to
https://github.com/loco-lab/hera-display-games
and close this issue.
